### ISSUE TITLE
Example request

### ISSUE THREAD

**Issue by HoiDam** [behind24proxies/PixelHub#1]
Caz im lazy. Is there any template provided? Thanks ;p

**Comment by behind24proxies** [comment]
hummm , what do you mean by template ?

**Comment by 0dayCTF** [comment]
I’m assuming they mean some examples, rather than creating the art themselves 🤷‍♂️

**Comment by behind24proxies** [comment]
hey , In the next couple of days I will make a new directory with some cool artworks (and the corresponding json strings as well)
btw, I just made this directory with fonts with less than 7px height (the maximum allowed)
https://github.com/behind24proxies/PixelHub/tree/main/pixel-font-ideas

**Comment by HoiDam** [comment]
Nice ;p
