### ISSUE TITLE
character input limit

### ISSUE THREAD

**Issue by ibnufachrizal** [behind24proxies/PixelHub#2]
1024 character input length limit when paste **enter the json string**

![CleanShot 2022-09-13 at 22 08 08](https://user-images.githubusercontent.com/26188697/189938208-33195c90-0efb-4d66-ae3e-945c49f6453e.png)

**Comment by behind24proxies** [comment]
it does not happen on windows.
here is a temporary fix 
https://github.com/behind24proxies/PixelHub/tree/main/1024-fix
just make a payload.txt file in the same directory as the script, and paste the json string there.

I will make the new release official as soon as possible
