### ISSUE TITLE
The command ran successfully but I cant see it?

### ISSUE THREAD

**Issue by Bhavye-Malhotra** [behind24proxies/PixelHub#3]
![image](https://user-images.githubusercontent.com/49281065/190563769-360603ac-036d-4153-8eb6-5575d30bb039.png)

## python script committed the changes but it didn't show on the graph.

![image](https://user-images.githubusercontent.com/49281065/190564338-c1f9d725-ba22-4d83-b045-cdc430bed848.png)

**Comment by behind24proxies** [comment]
can you send me the json string?

**Comment by Bhavye-Malhotra** [comment]
> 

{"2020-03-20":"zero","2020-01-25":"four","2020-01-24":"two","2020-01-23":"four","2020-01-22":"two","2020-01-21":"four","2020-01-30":"two","2020-02-06":"two","2020-02-13":"four","2020-02-11":"four","2020-02-12":"two","2020-02-14":"two","2020-02-15":"four","2020-02-29":"four","2020-03-06":"zero","2020-03-12":"three","2020-02-28":"four","2020-03-05":"four","2020-03-11":"zero","2020-03-04":"four","2020-03-10":"four","2020-03-18":"four","2020-03-19":"four","2020-03-27":"four","2020-03-28":"four","2020-04-08":"four","2020-04-14":"four","2020-04-21":"four","2020-05-05":"zero","2020-04-28":"two","2020-04-10":"four","2020-04-09":"two","2020-04-18":"four","2020-04-25":"four","2020-05-02":"two","2020-05-12":"four","2020-05-13":"two","2020-05-14":"four","2020-05-15":"two","2020-05-16":"four","2020-05-21":"four","2020-05-27":"three","2020-06-02":"two","2020-05-29":"three","2020-06-06":"two","2020-06-23":"four","2020-06-24":"zero","2020-06-16":"four","2020-06-17":"two","2020-06-18":"four","2020-06-19":"two","2020-06-20":"four","2020-06-25":"three","2020-07-04":"four","2020-06-27":"four","2020-06-30":"four","2020-07-02":"three","2020-07-14":"four","2020-07-15":"four","2020-07-16":"four","2020-07-17":"four","2020-07-18":"four","2020-07-21":"four","2020-07-28":"four","2020-08-05":"zero","2020-07-30":"zero","2020-07-23":"four","2020-07-31":"four","2020-08-08":"four","2020-08-07":"zero","2020-08-15":"zero","2020-07-29":"four","2020-07-24":"zero","2020-08-01":"zero"}

**Comment by behind24proxies** [comment]
I tried running it on my github and it worked, check my 2020 graph.
- try making a fresh public repository and doing the process again

- try making a local repo , adding a commit like this
` git commit -m "msg" --date="1-1-1970" --no-edit  `
and then pushing it to a remote repository , in under 1 hour you must see a green box in 1970, if you don't then you should contact github support and tell that you can't see commits on the contribution graph.

**Comment by Bhavye-Malhotra** [comment]
letme check
also how can i make this for some other year than 2020 ?

**Comment by Bhavye-Malhotra** [comment]
my bad your css is kind of broke i could see it 😂

**Comment by behind24proxies** [comment]
yeah the css is kind of broke, but this does not mean that you can't change the years
there is a dropdown on the top-right, change year , and then click the confirm button.

**Comment by behind24proxies** [comment]
I will fix the css the next week (hopefully)

**Comment by Bhavye-Malhotra** [comment]
> yeah the css is kind of broke, but this does not mean that you can't change the years there is a dropdown on the top-right, change year , and then click the confirm button.

yep got it

**Comment by Bhavye-Malhotra** [comment]
> I tried running it on my github and it worked, check my 2020 graph.
> 
> * try making a fresh public repository and doing the process again
> * try making a local repo , adding a commit like this
>   `git commit -m "msg" --date="1-1-1970" --no-edit `
>   and then pushing it to a remote repository , in under 1 hour you must see a green box in 1970, if you don't then you should contact github support and tell that you can't see commits on the contribution graph.

so i cant see my commits

**Comment by behind24proxies** [comment]
well, if that's the case than I can't do anything :(

**Comment by Bhavye-Malhotra** [comment]
> well, if that's the case than I can't do anything :(

I have put a ticker for GitHub support but ideally it should work if possible can u check it on a temp account.

**Comment by behind24proxies** [comment]
it should work on another account.
I tried creating a temp account , but they keep flagging it because it has the same ip as this one, same with nordVPN.
residential proxies are expensive :(

**Comment by behind24proxies** [comment]
I am closing this issue 
if you need any help, just open another one (or drop me an email)
